// <auto-generated />
using JOStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JOStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241220072955_CK_Entity_Id_NotZero")]
    partial class CK_Entity_Id_NotZero
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JOStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR")
                        .HasAnnotation("DisplayName", "Category Name");

                    b.HasKey("Id");

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_Entity_Id_NotZero", "[Id] <> 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "MOTHERBOARD"
                        },
                        new
                        {
                            Id = 2,
                            Name = "PROCESSOR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "GRAPHICS CARD"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
