// <auto-generated />
using JOStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JOStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241221142652_ProductTOCategoryRealtionShip")]
    partial class ProductTOCategoryRealtionShip
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Store.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_Entity_Id_NotZero", "[Id] <> 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "MOTHERBOARD"
                        },
                        new
                        {
                            Id = 2,
                            Name = "PROCESSOR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "GRAPHICS CARD"
                        });
                });

            modelBuilder.Entity("Store.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("CK_Entity_Id_NotZero", "[Id] <> 0")
                                .HasName("CK_Entity_Id_NotZero1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Brand: MSI, Model: A520M-A PRO, CPU Support: AMD Ryzen 5000 Series, 5000 G-Series, 4000 G-Series, 3000 Series and 3000 G-Series Processors, CPU Socket: AMD AM4, Chipset: AMD A520, Graphics Interface: 1x PCI-E 3.0 x16 Slot, Display Interface: HDMI, DVI-D – Requires Processor Graphics, Memory Support: 2 DIMMs, Dual Channel DDR4-4600MHz (OC)",
                            Name = "MSI A520M-A Pro Motherboard AM4",
                            Price = 2950.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Brand:AMD, Type: Processor, Processor Family: Ryzen 7, Processor Generation: 9800X3D, Socket Type: AM5, CPU Core: 8, Base Clock: 4.7GHz, Max Boost Clock: Up to 5.2GHz, Total L1 Cache: 640KB, Total L2 Cache: 8MB, Total L3 Cache: 96MB, Processor Graphics: Radeon Graphics 2200 MHz, Max Temperature: 95°C, Warranty: 3 Years ",
                            Name = "AMD Ryzen 7 9800X3D Processor (5.2GHz/104MB) 8 Core AM5",
                            Price = 27999.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Brand:Zotac Model: GeForce RTX 4060 Ti Twin Edge Type:GraphicsCardCoreClock: Boost:2535MHz,CUDA Cores: 4352,MemoryClock: 18 Gbps, Memory: 16GB - 128-bit - GDDR6",
                            Name = "Zotac Gaming GeForce RTX 4060 Ti Twin Edge 16GB GDDR6 Graphics Card",
                            Price = 23500.00m
                        });
                });

            modelBuilder.Entity("Store.Models.Product", b =>
                {
                    b.HasOne("Store.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Store.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
